name: Minutely Notebook Execution

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Permissions
        run: |
          echo $${{ secrets.GH_TOKEN_1 }}

      - name: List Git Configuration
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
        run: |
          git config --list --show-origin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Jupyter
        run: pip install jupyter

      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute Update_weekly_ranking.ipynb

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
        run: |
          git config --global user.email "jeanbouteiller.ds@gmail.com"
          git config --global user.name "jeanbouteiller-ds"
          git add "list_all_urls.txt"
          git add "list_all_players_names.txt"
          git add "df_player_fixed.csv"
          git add "Update_weekly_ranking.nbconvert.ipynb"
          git commit -m "Update files"
          git pull
          git push
