name: Minutely Notebook Execution

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Permissions
        run: |
          echo "GitHub Actions Token: $${{ secrets.GH_TOKEN }}"

      - name: List Git Configuration
        run: |
          git config --list

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Jupyter
        run: pip install jupyter

      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute test.ipynb
          python test.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "jeanbouteiller.ds@gmail.com"
          git config --global user.name "jeanbouteiller-ds"
          git add test_data.txt
          git commit -m "Update text file"
          git push
