name: Minutely Notebook Execution

on:
  schedule:
    - cron: "* * * * *"

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Jupyter
        run: pip install jupyter

      - name: Execute Notebook
        run: jupyter nbconvert --to notebook --execute test (1).ipynb
