name: Update Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Permissions
        run: |
          echo $${{ secrets.GH_TOKEN_1 }}
      - name: List Git Configuration
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
        run: |
          git config --list --show-origin
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Jupyter
        run: pip install jupyter

      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute workflow_notebooks/update_weekly.ipynb

      - name: Discard Local Changes
        run: git checkout "workflow_notebooks/update_weekly.nbconvert.ipynb"
          


      - name: Pull Remote Changes
        run: git pull origin main # Add this step to pull remote changes before committing

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.email "jeanbouteiller.ds@gmail.com"
            git config --global user.name "jeanbouteiller-ds"
            git add "data/df_all_ranking.csv"
            git add "data/df_all_betting.csv"
            git add "data/df_player_fixed.csv"
            git add "data/list_all_players_names.txt"
            git add "data/list_all_urls.txt"
            git add "workflow_notebooks/update_weekly.nbconvert.ipynb"
            git commit -m "Update files"
            git push
          else
            echo "No changes to commit."
          fi
